---
title: "Microbiota Analysis"
author: Sudarshan A. Shetty
date: "`r Sys.Date()`"
format:
  html:
    code-tools: true
    code-fold: false
    code-copy: true
    self-contained: true
    toc-location: left
knitr: 
    opts_chunk: 
        collapse: TRUE
        dpi: 150
        message: FALSE
        warning: FALSE
        error: TRUE
editor: visual

params:
    pseq_path: "data/FuentesIliGutData.rds"
    primary_var: "ILI"
---


```{r}
library(phyloseq)
library(microbiome)
library(ggpubr) # stats with viz
library(patchwork) # combine plots 
```

## Usage of parameters  
The parameters can be passed on simply as follows at the start of the code chunk
```{r}
pseq_path = params$pseq_path
primary_var = params$primary_var
```


## Read Data
```{r}
pseq <- readRDS(pseq_path)
print(pseq)
```

```{r}
# add reads/sample to sample_data()
sample_data(pseq)$reads.per.sample <- sample_sums(pseq)
# Compare between groups
pseq |> 
    microbiome::meta() |> 
    ggplot(aes_string(primary_var, "reads.per.sample")) +
    geom_violin()+
    geom_boxplot(width=0.2) +
    labs(x="", y="Reads/sample")
```

And rest of the analysis  